import ErrorWrapper from './error-wrapper'
import './globals.css'
export const metadata = {
    title: {
        default: 'Next.js App | Default Title',
        template: 'Next.js App | %s | Template title',
    },
    description: 'Generated by Next. js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <header
                    style={{
                        backgroundColor: "lightblue",
                        padding: "1rem",
                    }}>
                    <p>Header</p>
                </header>
                <ErrorWrapper>
                {children}
                </ErrorWrapper>
                <footer
                    style={{
                        backgroundColor: "ghostwhite",
                        padding: "1rem",
                        color: "gray",
                        fontWeight: "bold",
                    }}
                >
                    <p>Footer</p>
                </footer>

            </body>
        </html>
    )
}
